variables:
  BASE_IMAGE: "alpine:3.19"
  BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/branches/$CI_COMMIT_REF_SLUG-$TERRAFORM_VERSION:$CI_COMMIT_SHA"
  DOCKER_DIND_IMAGE: "docker:25.0-dind"
  RELEASE_IMAGE_NAME: "$CI_REGISTRY_IMAGE/releases/$TERRAFORM_VERSION"

.terraform-versions:
  parallel:
    matrix:
      - TERRAFORM_BINARY_VERSION: "1.7.2"
        TERRAFORM_VERSION: "1.7"
      - TERRAFORM_BINARY_VERSION: "1.6.6"
        TERRAFORM_VERSION: "1.6"
      - TERRAFORM_BINARY_VERSION: "1.5.7"
        TERRAFORM_VERSION: "1.5"

stages:
  - lint
  - build
  - release

dockerfile check:
  stage: lint
  image: hadolint/hadolint:latest-alpine
  before_script:
    - hadolint --version
  script:
    - hadolint Dockerfile

build terraform:
  extends: .terraform-versions
  stage: build
  services:
    - "$DOCKER_DIND_IMAGE"
  image: "$DOCKER_DIND_IMAGE"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build .
      --build-arg BASE_IMAGE=$BASE_IMAGE
      --build-arg TERRAFORM_BINARY_VERSION=$TERRAFORM_BINARY_VERSION
      --file Dockerfile
      --tag "$BUILD_IMAGE_NAME"
    - docker push "$BUILD_IMAGE_NAME"

release:
  extends: .terraform-versions
  stage: release
  services:
    - "$DOCKER_DIND_IMAGE"
  image: "$DOCKER_DIND_IMAGE"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$BUILD_IMAGE_NAME"
    - docker tag "$BUILD_IMAGE_NAME" "$CI_REGISTRY_IMAGE/releases/terraform:$TERRAFORM_BINARY_VERSION"
    - docker push "$CI_REGISTRY_IMAGE/releases/terraform:$TERRAFORM_BINARY_VERSION"