variables:
  BASE_IMAGE: "alpine:3.19"
  BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/branches/$CI_COMMIT_REF_SLUG-$TERRAFORM_VERSION:$CI_COMMIT_SHA"
  RELEASE_IMAGE_NAME: "$CI_REGISTRY_IMAGE/releases/$TERRAFORM_VERSION"
  STABLE_IMAGE_NAME: "$CI_REGISTRY_IMAGE/stable:latest"

.versions:
  parallel:
    matrix:
      - TERRAFORM_BINARY_VERSION: "1.7.1"
        TERRAFORM_VERSION: "1.7"
      - TERRAFORM_BINARY_VERSION: "1.6.6"
        TERRAFORM_VERSION: "1.6"
      - TERRAFORM_BINARY_VERSION: "1.5.7"
        TERRAFORM_VERSION: "1.5"
      - TERRAFORM_BINARY_VERSION: "1.4.6"
        TERRAFORM_VERSION: "1.4"

stages:
  - lint
  - build
  - release

dockerfile check:
  stage: lint
  image: hadolint/hadolint:latest-alpine
  before_script:
    - hadolint --version
  script:
    - hadolint Dockerfile

build terraform:
  extends: .versions
  stage: build
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build .
      --build-arg BASE_IMAGE=$BASE_IMAGE
      --build-arg TERRAFORM_BINARY_VERSION=$TERRAFORM_BINARY_VERSION
      --file Dockerfile
      --tag "$BUILD_IMAGE_NAME"
    - docker push "$BUILD_IMAGE_NAME"

release:
  extends: .versions
  stage: release
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker tag "$BUILD_IMAGE_NAME" "$RELEASE_IMAGE_NAME:latest"
    - docker push "$RELEASE_IMAGE_NAME:latest"
    - docker tag "$BUILD_IMAGE_NAME" "$CI_REGISTRY_IMAGE/releases/terraform:$TERRAFORM_BINARY_VERSION"
    - docker push "$CI_REGISTRY_IMAGE/releases/terraform:$TERRAFORM_BINARY_VERSION"